# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-17 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prendas',
            options={'verbose_name': 'Prendas', 'verbose_name_plural': 'Prendas'},
        ),
    ]
